# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-06-15 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidLoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('login_ip', models.GenericIPAddressField()),
            ],
            options={
                'db_table': 'LBARM_LOGIN_INVALID_LOG',
            },
        ),
        migrations.CreateModel(
            name='LBARMProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'LBARM_USER_PROFILE',
                'ordering': ('user__username',),
            },
        ),
        migrations.CreateModel(
            name='LBARMTipoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_utilizador', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Utilizador',
                'verbose_name_plural': 'Tipos Utilizador',
                'db_table': 'LBARM_TIPO_USER',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('login_ip', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LBARM_LOGIN_LOG',
            },
        ),
        migrations.AddField(
            model_name='lbarmprofile',
            name='tipo_utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.LBARMTipoUser', verbose_name='Tipo de Utilizador'),
        ),
        migrations.AddField(
            model_name='lbarmprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
