# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-26 12:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backoffice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDataPerm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(max_length=50)),
                ("empresa_bo", models.CharField(max_length=60)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_data_perm",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userdataperm",
            unique_together=set([("user", "empresa", "bo")]),
        ),
    ]
