export enum Permission {
  SALES_FORECAST = 'SALES_FORECAST',
  SALES = 'SALES',
  STOCK = 'STOCK',
  PURCHASE = 'PURCHASE',
  ORDER_SUMMARY = 'ORDER_SUMMARY',
  PREV_LOG = 'PREV_LOG',
  CHANGE_LOG = 'CHANGE_LOG',
}
