# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-08-20 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovedOrderRequests",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                ("data_do_pedido", models.DateField()),
                ("utilizador_id", models.BigIntegerField()),
                ("utilizador", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_approved_orders",
            },
        ),
        migrations.CreateModel(
            name="BasicAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(max_length=50)),
                ("cardcode", models.CharField(max_length=15)),
                ("fornecedor", models.CharField(max_length=100)),
                ("familia", models.CharField(max_length=100)),
                ("artigo", models.CharField(max_length=50)),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("numero_encomenda", models.CharField(max_length=19)),
                ("data_encomenda", models.DateTimeField()),
                ("previsao_data_envio", models.DateTimeField()),
                ("previsao_data_entrega", models.DateTimeField()),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "qt_encomendada",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=19, null=True
                    ),
                ),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_basic_agreement",
            },
        ),
        migrations.CreateModel(
            name="ForecastManualChangeLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField()),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("origem_forecast", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("utilizador_id", models.BigIntegerField()),
                ("utilizador", models.CharField(max_length=50)),
                ("comentario", models.TextField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=17, null=True
                    ),
                ),
                ("prev_qt_u", models.DecimalField(decimal_places=4, max_digits=17)),
                ("prev_qt_cx", models.DecimalField(decimal_places=4, max_digits=17)),
                ("prev_qt_cx9", models.DecimalField(decimal_places=4, max_digits=17)),
                (
                    "parent_request",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prev_log.ForecastManualChangeLog",
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_manual_change_log",
            },
        ),
        migrations.CreateModel(
            name="OpenOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(max_length=50)),
                ("fornecedor", models.CharField(max_length=100)),
                ("familia", models.CharField(max_length=100)),
                ("artigo", models.CharField(max_length=50)),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("previsao_data_entrega", models.DateTimeField()),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_open_order",
            },
        ),
        migrations.CreateModel(
            name="OrigemPrevisao",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designacao", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "Origem Operação",
                "verbose_name_plural": "Origens Operação",
                "db_table": "prev_log_origem",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("planingsys", models.CharField(blank=True, max_length=1, null=True)),
                ("lead_time", models.IntegerField(blank=True, null=True)),
                (
                    "min_ordr_qty",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=19, null=True
                    ),
                ),
                (
                    "ordr_multi",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=19, null=True
                    ),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=38, null=True
                    ),
                ),
                (
                    "stock_actual",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=38, null=True
                    ),
                ),
                (
                    "stock_reservado",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=38, null=True
                    ),
                ),
                (
                    "stock_encomendado",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=38, null=True
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_product",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(max_length=50)),
                ("fornecedor", models.CharField(max_length=100)),
                ("familia", models.CharField(max_length=100)),
                ("artigo", models.CharField(max_length=50)),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("docdate", models.DateField()),
                ("anodocdate", models.IntegerField()),
                ("mesdocdate", models.IntegerField()),
                ("taxdate", models.DateField()),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_purchase",
            },
        ),
        migrations.CreateModel(
            name="PurchaseForecast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("data_limite_pedido", models.DateTimeField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prev_log.OrigemPrevisao",
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_purchase_forecast",
            },
        ),
        migrations.CreateModel(
            name="PurchaseForecastOpenRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("utilizador_id", models.BigIntegerField()),
                ("utilizador", models.CharField(max_length=50)),
                ("comentario", models.TextField()),
                ("created_at", models.DateTimeField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prev_log.ForecastManualChangeLog",
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_request_purchase_forecast",
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(max_length=50)),
                ("canal", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=100)),
                ("familia", models.CharField(max_length=100)),
                ("artigo", models.CharField(max_length=50)),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "capacidade",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=19, null=True
                    ),
                ),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_sale",
            },
        ),
        migrations.CreateModel(
            name="SaleForecast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prev_log.OrigemPrevisao",
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_sale_forecast",
            },
        ),
        migrations.CreateModel(
            name="SaleForecastOpenRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("utilizador_id", models.BigIntegerField()),
                ("utilizador", models.CharField(max_length=50)),
                ("comentario", models.TextField()),
                ("created_at", models.DateTimeField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prev_log.ForecastManualChangeLog",
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_request_sale_forecast",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dia", models.DateField()),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(max_length=50)),
                ("marca", models.CharField(max_length=100)),
                ("rotulo", models.CharField(max_length=100)),
                ("familia", models.CharField(max_length=100)),
                ("artigo", models.CharField(max_length=50)),
                ("descricao", models.CharField(blank=True, max_length=200, null=True)),
                ("armazem", models.CharField(max_length=8)),
                (
                    "stock_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "stock_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "stock_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_stock",
            },
        ),
        migrations.CreateModel(
            name="StockForecast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prev_log.OrigemPrevisao",
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_stock_forecast",
            },
        ),
        migrations.CreateModel(
            name="StockForecastOpenRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("utilizador_id", models.BigIntegerField()),
                ("utilizador", models.CharField(max_length=50)),
                ("comentario", models.TextField()),
                ("created_at", models.DateTimeField()),
                (
                    "qt_u",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "qt_cx9",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="prev_log.ForecastManualChangeLog",
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_request_stock_forecast",
            },
        ),
        migrations.CreateModel(
            name="Tendency",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=2)),
                ("bo", models.CharField(blank=True, max_length=50, null=True)),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                ("artigo", models.CharField(max_length=50)),
                (
                    "tendencia_ponderada",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=17, null=True
                    ),
                ),
                (
                    "base_anual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=17, null=True
                    ),
                ),
                (
                    "media_anual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "tendencia_anual",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=17, null=True
                    ),
                ),
                (
                    "media_trimestral",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=17, null=True
                    ),
                ),
                (
                    "tendencia_trimestral",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=17, null=True
                    ),
                ),
            ],
            options={
                "db_table": "prev_log_tendency",
            },
        ),
        migrations.AlterUniqueTogether(
            name="tendency",
            unique_together=set([("artigo", "familia", "bo")]),
        ),
        migrations.AlterUniqueTogether(
            name="stock",
            unique_together=set([("dia", "empresa", "bo", "artigo", "armazem")]),
        ),
        migrations.AlterUniqueTogether(
            name="sale",
            unique_together=set(
                [("empresa", "bo", "canal", "nome", "artigo", "ano", "mes")]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchase",
            unique_together=set(
                [("empresa", "bo", "fornecedor", "artigo", "docdate", "taxdate")]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together=set([("empresa", "artigo")]),
        ),
        migrations.AlterUniqueTogether(
            name="openorder",
            unique_together=set(
                [
                    (
                        "empresa",
                        "bo",
                        "fornecedor",
                        "artigo",
                        "previsao_data_entrega",
                        "ano",
                        "mes",
                    )
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="basicagreement",
            unique_together=set(
                [
                    (
                        "empresa",
                        "bo",
                        "cardcode",
                        "fornecedor",
                        "artigo",
                        "numero_encomenda",
                        "data_encomenda",
                        "previsao_data_envio",
                        "previsao_data_entrega",
                    )
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockforecastopenrequest",
            unique_together=set(
                [("artigo", "familia", "bo", "ano", "mes", "utilizador", "created_at")]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockforecast",
            unique_together=set([("artigo", "familia", "bo", "ano", "mes")]),
        ),
        migrations.AlterUniqueTogether(
            name="saleforecastopenrequest",
            unique_together=set(
                [("artigo", "familia", "bo", "ano", "mes", "utilizador", "created_at")]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="saleforecast",
            unique_together=set([("artigo", "familia", "bo", "ano", "mes")]),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseforecastopenrequest",
            unique_together=set(
                [("artigo", "familia", "bo", "ano", "mes", "utilizador", "created_at")]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="purchaseforecast",
            unique_together=set([("artigo", "familia", "bo", "ano", "mes")]),
        ),
        migrations.AlterUniqueTogether(
            name="forecastmanualchangelog",
            unique_together=set(
                [("artigo", "familia", "bo", "ano", "mes", "created_at", "utilizador")]
            ),
        ),
    ]
